source 'http://rubygems.org'

gem 'rails', '2.2.2'
gem 'pg', '0.9.0'
gem 'googlebase', '0.2.1'
gem 'paperclip', '2.1.2'
gem "httparty", '0.5.2'
gem "RedCloth", '4.2.3'
gem "days_and_times", '1.0.2'
# gem "quickbooks", ''
# gem 'mongo_mapper', '0.6.1'
gem 'navvy', '0.1.0'